<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class HRConnection extends Model
{
    protected $connection = 'mysqlhrconnection';
    protected $table = 'users';
    protected $fillable = [
        'number_employee',
        'last_name_kh',
        'first_name_kh',
        'last_name_en',
        'first_name_en',
        'employee_name_kh',
        'employee_name_en',
        'role_id',
        'position_id',
        'position_type',
        'department_id',
        'branch_id',
        'profile',
        'unit',
        'level',
        'line_manager',
        'gender',
        'date_of_birth',
        'id_card_number',
        'id_number_nssf',
        'nationality',
        'ethnicity',
        'date_of_commencement',
        'guarantee_letter',
        'employment_book',
        'identity_type',
        'identity_number',
        'issue_date',
        'issue_expired_date',
        'type_of_employees_nssf',
        'spouse_nssf',
        'status_nssf',
        'is_type_nssf',
        'current_province',
        'current_district',
        'current_commune',
        'current_village',
        'current_house_no',
        'current_street_no',
        'permanent_province',
        'permanent_district',
        'permanent_commune',
        'permanent_village',
        'permanent_house_no',
        'permanent_street_no',
        'company_phone_number',
        'personal_phone_number',
        'agency_phone_number',
        'marital_status',
        'fdc_date',
        'fdc_end',
        'severance_pay_date',
        'udc_end_date',
        'resign_date',
        'resign_reason',
        'remark',
        'spouse',
        'bank_name',
        'account_name',
        'account_number',
        'users_permission',
        'status',
        'emp_status',
        'p_status',
        'is_loan',
        'type',
    ];
}
